### ISSUE TITLE
fontblocker does not add new fonts in options

### ISSUE THREAD

**Issue by raven428** [rudiedirkx/FontBlocker#22]
hello. thank you for useful extension, but I found fatal issue.

after addings some fonts and sites to block list in options, fontblocker stops adding there new fonts to list in options.

to replay this issue try this:
1. clear extenstion options by removing it and adding back to chrome;
2. import [this](https://gist.github.com/raven428/7f819cbbe67ca99c250b83cfd28bcec6) through the import form;
3. try to block new font somewhere or import something new through the import form.

when you'll try to block font on some webpage, it will be blocked. but after reloading webpage will use blocked font again. this happens because fontblocker just blocks font and does not add it to their block list in options.

when you will try to import something new (after import my gist), there will be no result. list of new websites and fonts to block will not be added to block list.

**Comment by rudiedirkx** [comment]
Ah. Yes. According to [the docs](https://developer.chrome.com/extensions/storage#property-sync) an extension can only store 100K (not the problem), with max 8K per item. That 8K is the problem, because I store all blocked fonts in 1 item, so you can only have 8K of blocked fonts.

I can probably hack around this some nasty way, but I'll have to think about it. For now, your 117 fonts seems so be the max.

Btw, the more blocked fonts, the slower every page gets, because every page load checks all 117 fonts for a match. I only block fonts for websites where I go often.

I'll let you know when I've fixed it.

**Comment by rudiedirkx** [comment]
You can also 'globalize' a blocked font and remove the site specific blocks. If you have font X blocked on 8 websites (like I have `Roboto` and `Open Sans`) that's space efficient.

All excuses of course! I'll fix it.

**Comment by raven428** [comment]
storage with 100k bytes may be small too. could you please make option to choose storage.sync or storage.local? thank you.

**Comment by rudiedirkx** [comment]
If 8K is 117 fonts, 100K is 1462 fonts. If you have more than 1462 blocked fonts, you're doing something wrong.

Until it's fixed, you'll have to remove some fonts to add others.
