### ISSUE TITLE
Keep weight & style

### ISSUE THREAD

**Issue by rudiedirkx** [rudiedirkx/FontBlocker#25]
Since an **entire** font family is replaced by Arial, **bold** and _italic_ are gone.

Is there some way to replace `SomeFont italic 700` with `Arial italic 700` ? Or just italic or not, and bold or not. No need for all variants.

Test page: https://webblocks.nl/tests/fonts.html

**Comment by jay** [comment]
I have a stylish script in firefox which does that, I think. ~~I don't remember if I actually tested bold/italic/etc variants.~~ _(edit: just tested it and it does work to replace one bold with a different bold)_

See https://gist.github.com/jay/e99fe4fe7e7bd4feaf5f237e15717133

for example segoe ui bold -> arial bold
~~~css
@font-face {
font-family: "Segoe UI";
font-weight: bold;
font-style: normal;
src: local("Arial Bold");
}
~~~

**Comment by rudiedirkx** [comment]
I've tried `Arial Bold` locally a while ago, and I don't think that worked. Will do some more testing right now. Maybe casing matters, or OS.

Also, wow, how are you this fast? What are you doing here? I was just talking to myself, I thought =)

**Comment by jay** [comment]
I am watching your repo so I am subscribed new issues when they are opened. I use your extension in Chrome to get rid of some annoying fonts. i'm using it to replace the web font on amazon. for the most part i don't notice the missing bold

I use my css replacement script on github in firefox and also I just checked the bold and italic variants and they are converted properly, I can see it in the inspector's computed styles section. Not sure if it will translate to chrome though.
![capture](https://user-images.githubusercontent.com/965580/34472789-a2684eaa-ef37-11e7-854a-9e8cd5624d44.PNG)

custom weight numbers i imagine would be more complicated but i'd guess just bold would cover a lot

**Comment by rudiedirkx** [comment]
Yeah, the numbers screw something up, but that's strange, because I've caught all variants with their own `@font-face`. 100-400 are normal and 500-900 are bold. Github overrides `strong` a few times:

```
strong {
    font-weight: 600;
}
strong {
    font-weight: bolder;
}
strong {
    font-weight: inherit;
}
```

The 600 wins, but I have a rule for that:

```
@font-face { font-family: "-apple-system"; font-weight: 600; font-style: normal; src: local("Arial Bold"); }
```

but that doesn't work... If I disable Github's 600 in Devtools, `bolder` is trigger, which I don't catch, so it's bold again. If I disable that, and `inherit` too, normal `bold` runs, and I catch that and that works like expected.

I'm curious if I can catch `bolder`. Apparently not `600`...

My Devtools keeps saying it's rendering `Segoe UI`, wth... Whichever font is active, Devtools thinks it's rendering `Segoe UI`. Super useful.

**Comment by rudiedirkx** [comment]
Weird. The normal characters are Arial, but the bold and italic are `Segoe UI`.

![image](https://user-images.githubusercontent.com/168024/34472933-50b41348-ef6c-11e7-8796-e348304ea466.png)

If I remove `Segoe UI` from the `.markdown-body`'s `font-family`, all works as I expect. Why does Segoe UI win from my `-apple-system` override??

**Comment by rudiedirkx** [comment]
I give up. New commit kinda works, but not on Github. If you figure it out, kudo's.

**Comment by rudiedirkx** [comment]
Version 1.17

**Comment by jay** [comment]
I tested 1.17 but something weird is happening. Either the font doesn't change or it changes to something like times new roman. I have examined the source injected into the page and it looks correct so I'm at a loss for the cause. I suspect it may be a limitation in Chrome, or DirectWrite (since DW does not recognize some arial variants apparently.. and I don't use DirectWrite in Firefox I think which would explain why Arial Bold works there).

For example I tested against an amazon listing https://www.amazon.com/gp/product/B01LZEVDKI

---

Here's what it looks like in 8b49f0c 2017-05-03:

![before](https://user-images.githubusercontent.com/965580/35031892-d2e028f8-fb32-11e7-9e42-f9246490dbb2.png)

---

Here's what it looks like in (1.17) 27cd8b8 2018-01-04:

![after](https://user-images.githubusercontent.com/965580/35031899-d8058abc-fb32-11e7-8d0c-e38cc9034a83.png)
![after source](https://user-images.githubusercontent.com/965580/35031908-dc8a08d8-fb32-11e7-9d59-6e67edf555f0.PNG)

---

Changing it to `Arial Bold` doesn't work either, though as I mentioned it works in Firefox. Does `Arial Bolder` work for you on Mac? Also, if you'd prefer I can open a new issue with this content.

edit: The test was done in Windows 7 Enterprise w/ cleartype disabled and Chrome 63.0.3239.108 (Official Build) (64-bit)

**Comment by rudiedirkx** [comment]
The only difference between the 2 screenshots that I can see is the boldness. That was the point. I don't see any strange fonts, or New Times Roman.

Since 1.17 you can change the replacement font on the settings page. Times New Roman is one of them. Maybe that's the reason? Works fine for me, always `Arial` by default, but maybe it doesn't.

It was never supposed to be `Bolder`. It was supposed to be `Bold`. The `Bolder` was a test that I forgot to change back, that apparently always works for me.... I have no Mac to test on, so I'm flying blind there.

1.17 didn't work perfectly for me either, but it failed differently from your experience. I'll change `Bolder` to `Bold`, but that's not release worthy, unless it's now broken on all Mac or all Firefox or something. Works fine for me though...

It's all still part of the 'weight & style' issue, so let's keep it here.

Any ideas, beyond changing `Bolder` to `Bold`?

**Comment by jay** [comment]
> The only difference between the 2 screenshots that I can see is the boldness. That was the point. I don't see any strange fonts, or New Times Roman.

The font is bold but as you can see in computed styles it's using Amazon Ember not the Arial replacement. So the problem is not that it's bold but that the substitution doesn't take place. The other problem since the update is where the wrong substitution takes place on a [tv listings website](https://tvlistings.zap2it.com/?aid=gapzap). I tried substituting the font for program name from Gotham to Arial, but as you can see in computed styles it's using Times New Roman as a substitute and also it's not bold.

![substitute for gotham doesn t work properly](https://user-images.githubusercontent.com/965580/35140670-16162796-fcc6-11e7-94dc-65313147265e.png)

> Any ideas, beyond changing Bolder to Bold?

Either issue could be due to a bug in Chrome in Windows? I will try to reproduce with a bare bones webpage when I can.

**Comment by jay** [comment]
I've since upgraded to 1.19 and noticed that the style/weight support was removed (as described in #30). I've been experimenting and this seems to work ok in Chrome in Windows, tested on amazon.com:

~~~diff
diff --git a/fontblocker.content.js b/fontblocker.content.js
index 8ca73d9..de1d626 100644
--- a/fontblocker.content.js
+++ b/fontblocker.content.js
@@ -40,7 +40,10 @@ function addFonts(fonts, replacements, type, manual) {
 		var font = fonts[i];
 		var replacementFont = replacements[i] || fb.REPLACEMENT;
 
-		css.push('@font-face { font-family: "' + font + '"; src: local("' + replacementFont + '"); }');
+		css.push('@font-face { font-family: "' + font + '"; src: local("Arial"); }');
+		css.push('@font-face { font-family: "' + font + '"; font-style:italic; src: local("Arial Italic"); }');
+		css.push('@font-face { font-family: "' + font + '"; font-weight:700; src: local("Arial Bold"); }');
+		css.push('@font-face { font-family: "' + font + '"; font-style:italic; font-weight:700; src: local("Arial Bold Italic"); }');
 	}
 
 	// Insert into DOM
@@ -51,12 +54,17 @@ function addFonts(fonts, replacements, type, manual) {
 	style.dataset.count = fonts.length;
 	style.innerHTML = css.join("\n");
 	(document.head || document.documentElement).appendChild(style);
+	var style2 = style.cloneNode(true);
+	document.body.appendChild(style2);
 
 	// Make sure it keeps being last
 	var move = function() {
 		if ( style.nextElementSibling && !style.nextElementSibling.classList.contains('fontblocker') ) {
 			(document.head || document.documentElement).appendChild(style);
 		}
+		if ( style2.nextElementSibling && !style2.nextElementSibling.classList.contains('fontblocker') ) {
+			document.body.appendChild(style2);
+		}
 
 	};
 	var mover = function() {
~~~

I don't know if it's necessary to append to the body as well but I was trying different things because some websites put styles in the body. I've filed a chromium [report](https://bugs.chromium.org/p/chromium/issues/detail?id=1152700) asking that they create a more reliable way to override than font-face, which can itself be overridden.

---

Update: They closed my Chromium report for one that's been open for 3 years with no traction, so I don't think they're going to do much about it. A way to check substitution could be to render it then try to retrieve the render from the element? Today I'm trying the loop from 1.18 in 1.19 which works ok. I found one bug, `font-weight: bolder`  isn't valid so those substitutions are basically interpreted as substitute replacement font in bold for normal font `foo`. Eg substitute Arial Bold for Amazon Ember. So I removed `bolder` from the list.
